{% set name = "pymc-marketing" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymc-marketing-{{ version }}.tar.gz
  sha256: 1e9d1f177aa8905e94389a33add6e033d11acdb961b50bc26779a9b9500949db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - arviz >=0.13.0
    - matplotlib-base >=3.5.1
    - numpy >=1.17
    - pandas
    - pymc >=5.7.1
    - scikit-learn >=1.1.1
    - seaborn >=0.12.2
    - xarray
    - xarray-einstats >=0.5.1

test:
  imports:
    - pymc_marketing
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Marketing Statistical Models in PyMC
  home: https://github.com/pymc-labs/pymc-marketing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - twiecki
    - ricardoV94
    - drbenvincent
