{% set name = "pymc-marketing" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b4e204e6dec2d414083fe473c54d5f24e07934a888dad1d3fa9fc0380f6a438f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - pydantic >=2.1.0
    - python >=3.10
    - arviz >=0.13.0
    - matplotlib-base >=3.5.1
    - numpy >=1.17
    - pandas
    - pymc >=5.13.0,<5.16.0
    - scikit-learn >=1.1.1
    - seaborn >=0.12.2
    - xarray
    - xarray-einstats >=0.5.1

test:
  imports:
    - pymc_marketing
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Marketing Statistical Models in PyMC
  home: https://github.com/pymc-labs/pymc-marketing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - twiecki
    - ricardoV94
    - drbenvincent
